CartoDB/raster-loader

- .env
- CONTRIBUTING.md
- Makefile
- docker-compose.yml
- docker/raster_loader/Dockerfile
Related to #58 
Add a `docker-compose` based docker development environment for raster_loader with associated commands in the Makefile.
This PR add the following new commands to the Makefile:
- `docker-build`:  Build necessary stuff.
- `docker-start`: Start container with docker-compose and attach to logs.
- `docker-test`: Enter the running raster_loader container and run tests.
- `docker-enter`: Enter the raster_loader container.
- `docker-stop`: Stop container
I added the `docker-` prefix to these commands just to keep other existing commands intact, but moving forward we could switch all Makefile commands to interact with the Docker environment and drop the `docker-` prefix.
> added a basic docker-compose based dev environment

- raster_loader/io.py
- raster_loader/tests/mocks.py
- raster_loader/tests/test_io.py
If the user supplies an invalid CRS, or the CRS doesn't match the metadata of the raster, then the `rasterio.errors.CRSError` is thrown.
Also implemented unittest which supplies invalid CRS code and asserts the correct exception is raised.
Fixes #89
> Raise rasterio.errors.CRSError for invalid CRS and Add test error condition (#89)

- docs/source/user_guide/cli.rst
- docs/source/user_guide/use_with_python.rst
- raster_loader/cli/bigquery.py
- raster_loader/io.py
Related to #72 
Add information about the quadbin parameters for the CLI and Python module
> Update docs for quadbin

- raster_loader/io.py
- raster_loader/tests/test_io.py
> Change the endianess to little endian to accomodate the front end

- docker/raster_loader/Dockerfile
Fixes #103 
Avoid installing GDAL twice resulting in having installed an unexpected version of GDAL.
N/A
> Dockerfile - avoid installing GDAL twice

- raster_loader/io.py
Fixes #
[sc-306621]
I'm adding resolution to the field metadata only in the case we are uploading quadbins. When appending tables, any_value is taken.
> Chore/sc 306096/add level to raster metadata

- raster_loader/io.py
- raster_loader/tests/test_io.py
Fixes #
https://app.shortcut.com/cartoteam/story/307121/handle-nodata-values-in-raster-loader
This PR adds the nodata value of the raster layer to the table metadata
- [ x] I have tested the changes locally
- [ x] I have added tests to cover my changes (if applicable)
> fix: store raster nodata value in table metadata

- raster_loader/cli/bigquery.py
- raster_loader/io.py
Fixes #
- https://app.shortcut.com/cartoteam/story/341001/add-option-append-to-raster-loaders
Just added an option to skip the append data check.
> add append option to skip check

- raster_loader/io.py
Story details: https://app.shortcut.com/cartoteam/story/357569
> fix(raster-loader|bq): Round JSON_PARSE by default

- raster_loader/errors.py
- raster_loader/io.py
- raster_loader/tests/test_io.py
- Add `pixel_resolution` attribute to the metadata (will be used by the AT)
- Rename `resolution` attribute to `block_resolution`.
> feat: add pixel_resolution, rename block_resolution

- raster_loader/io.py
Ensure that the metadata field `pixel_resolution` is an integer.
> fix: metadata field pixel_resolution as an integer

- raster_loader/io.py
Rasters with input resolution greater than 26 are not supported by the AT. In this case we raise an error.
> chore: raise error when pixel resolution greater than 26

- raster_loader/io/bigquery.py
- raster_loader/tests/bigquery/test_io.py
Adding a `raster_loader` label to BQ tables containing the current package version
> Add labels to BQ uploaded tables

- raster_loader/errors.py
- raster_loader/io/bigquery.py
- raster_loader/io/common.py
If raster-loader is installed without the optional bigquery dependencies if fails with uncontrolled error even if bigquery not used:
```
Traceback (most recent call last):
File "/Users/ernesto/cartodb/rasterenv/bin/carto", line 5, in <module>
from raster_loader.cli import main
File "/Users/ernesto/cartodb/raster-loader/raster_loader/__init__.py", line 3, in <module>
from raster_loader.io.bigquery import (
File "/Users/ernesto/cartodb/raster-loader/raster_loader/io/bigquery.py", line 33, in <module>
class AccessTokenCredentials(Credentials):
^^^^^^^^^^^
NameError: name 'Credentials' is not defined    
```
Prevent the uncontrolled error; if bigquery is used and the depencies are not available fail with the same error message as before the bug was introduced:  
```
Google Cloud BigQuery is …
```
> fix: error when bigquery dependencies not installed

- raster_loader/cli/bigquery.py
- raster_loader/cli/snowflake.py
- raster_loader/io/bigquery.py
- raster_loader/io/snowflake.py
When a raster upload fails, we're asking for a yes/no input to cleanup the recently uploaded resources
When this happens in a non-interactive context like import worker, the process gets stuck
The objective of these changes is to add a `--cleanup-on-failure` parameter to skip the question for all providers
> Add a argument to skip interactive question on upload failure

- raster_loader/io/common.py
In some cases, we can not use the function `shapely.wkt.loads` importing only shapely.
```
$ python
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapely
>>> shapely.__version__
'2.0.3'
>>> shapely.wkt.loads
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'shapely' has no attribute 'wkt'
>>> from shapely import wkt
>>> wkt.loads
<function loads at 0x7fa5eb5ccc10>
```
I've introduced a change to import `wkt` and then use `wkt.loads`.
> fix: shapely.wkt import

- docs/source/user_guide/cli.rst
- raster_loader/cli/bigquery.py
- raster_loader/cli/snowflake.py
- raster_loader/io/datawarehouse.py
- raster_loader/io/snowflake.py
- raster_loader/tests/bigquery/test_io.py
- raster_loader/tests/snowflake/test_io.py
We have observed that users face the following error frequently:
```
Error: Error uploading to BigQuery: [Forbidden('Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas')]
```
Increasing the chunk size will prevent this error from happening in most cases, although the parallelization will be reduced.
NOTE: when this is released, we will need to update the value in the public docs: https://docs.carto.com/data-and-analysis/analytics-toolbox-for-bigquery/guides/working-with-raster-data#options-for-very-large-files
> increase chunk-size to 10000

- docs/source/user_guide/cli.rst
- docs/source/user_guide/use_with_python.rst
- raster_loader/errors.py
* Use `-co OVERVIEWS=IGNORE_EXISTING` so that overviews are generated
* keep `-co ADD_ALPHA=NO` as the safest general choice (but it would be recommended to convert exiting nodata values to an alpha band with the GTiff driver and use `ADD_ALPHA=YES`
> fix: make the gdalwarp examples consistent

- raster_loader/io/common.py
```
Received: "Command failed: carto snowflake upload --file_url https://storage.googleapis.com/carto_test_tables/raster/medium_cog.tif --database CI --schema CI_TMP_UPLOADS --table TEST_23C23309B13257C3A0381475 --account sxa81489.us-east-1·
Traceback (most recent call last):
File \"/usr/local/bin/carto\", line 5, in <module>
from raster_loader.cli import main
File \"/usr/local/lib/python3.9/dist-packages/raster_loader/__init__.py\", line 3, in <module>
from raster_loader.io.bigquery import (
File \"/usr/local/lib/python3.9/dist-packages/raster_loader/io/bigquery.py\", line 10, in <module>
from raster_loader.io.common import (
File \"/usr/local/lib/python3.9/dist-packages/raster_loader/io/common.py\", line 34, in <module>
\"float16\": np.NaN,
File …
```
> fix: support NumPy 2.0

- .gitignore
- raster_loader/io/common.py
chore: Update .gitignore
add: Add quantiles and top_values stats to the band level metadata in the common.py.
Fixes #
[Link the issue this PR is based on. All PRs need to be associated to at least
one issue in the issue tracker.]
[Summarize the changes this PR contains. Describe how these changes resolve or
help resolve the issue linked above.]
[Anything else you'd like to include.]
Metadata example:
{'min': 0.0, 'max': 255.0, 'mean': 46.78931471701873, 'stddev': 44.4161335121091, 'sum': 7513241.0, 'sum_squares': 668322593.0, 'quantiles': {3: [0, 66], 4: [0, 48, 75], 5: [0, 31, 60, 81], 6: [0, 0, 48, 66, 86], 7: [0, 0, 37, 57, 71, 90], 8: [0, 0, 25, 48, 62, 75, 93], 9: [0, 0, 0, 40, 55, 66, 78, 95], 10: [0, 0, 0, 31, 48, 60, 70, 81, 97], 11: [0, 0, 0, 21, 42, 54, 63, 73, 84, 99], 12: [0, …
> Add metadata for Builder Rasters

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- requirements-dev.txt
- setup.cfg
Python 3.8 has reached its EOL. For this reason and for compatibility with `rasterio` library, we need to stop giving support to this python version.
We have removed the CI pipeline that takes care of the python 3.8 version and added support for python 3.12.
In order to support python 3.12, `flake8` and its dependency `importlib-metadata` have been updated, and `setuptools` has been added as a dependency in `requirements-dev.txt` as it is used during testing.
In addition, we have updated the setup and the documentation so that they reflex these changes.
> chore: remove support for python3.8 and add 3.12

- .env
- CHANGELOG.md
- raster_loader/cli/bigquery.py
- raster_loader/cli/snowflake.py
- raster_loader/io/bigquery.py
- raster_loader/io/common.py
- raster_loader/io/snowflake.py
- raster_loader/tests/bigquery/test_cli.py
- raster_loader/tests/snowflake/test_cli.py
https://app.shortcut.com/cartoteam/story/456192/top-value-parameter-should-be-present-by-default-in-raster-loader
We have reversed the `--all_stats` flag into the `--omit_stats` in both `bigquery` and `snowflake` CLIs.
The new logic is that of calculate both top_values and quantiles by default and only omit them if specify by user `--omit_stats`.
In addition, we have fixed some other issues when:
1. Dealing with very sparse raster
2. Computing mean and stdev for exact stats
3. Colorinterp name
> Bug/sc 456192/top value parameter should be present by default

- raster_loader/cli/snowflake.py
- raster_loader/io/snowflake.py
- raster_loader/tests/snowflake/test_cli.py
- raster_loader/utils.py
Snowflake key pair authentication support. See: [Key-pair authentication](https://docs.snowflake.com/en/user-guide/key-pair-auth)
2 new options added to snowflake commands: 
`--private-key-path`: Path to your privake key in PEM format
`--private-key-passphrase`: Passphrase for private key if it's encrypted (optional)
Example:
```
carto snowflake upload \
--file_url https://... \
--database my-snowflake-database \
--schema my-snowflake-schema \
--table my-snowflake-table \
--account my-snowflake-account \
--warehouse my-warehouse \
--username my-snowflake-user \
--private-key-path /path/to/my/privatekey.pem \
--private-key-passphrase my-passphrase \
--band 1 \
--cleanup-on-failure \
--overwrite
```
> Feature/sc 455513/allow using key pair credentials in raster

- raster_loader/io/common.py
Fixes #
- Fixed most_common_approx function: duplicated counts variable definition. Causing this error:
```carto bigquery upload   --file_path ~/Downloads/raster/blended_output_cog.tif   --project cartobq   --dataset cayetanobv_raster_tests   --table blended_output_compress --overwrite --compress --band 1 --band 2 --band 3
Preparing to upload raster file to BigQuery...
File Path: /home/cayetano/Downloads/raster/blended_output_cog.tif
File Size: 3279.5174951553345 MB
Number of bands: 3
Band types: ('uint8', 'uint8', 'uint8')
Band sizes (MB): [4096.0, 4096.0, 4096.0]
Source Band: (1, 2, 3)
Band Name: [None, None, None]
Number of Blocks: 65536
Block Dims: (256, 256)
Project: cartobq
Dataset: cayetanobv_raster_tests
Table: blended_output_compress
Number of Records Per BigQuery Append: 10000 …
```
> fix: most_common_approx duplicated counts definition

- raster_loader/errors.py
Just adding a missing blank space between the suggested gdalwarp command options.
There is a missing space between options:
So if you simply copy-paste the suggested command and replace the files, you'll get an error.
> Fix typo in suggested command in error message

- raster_loader/io/common.py
The `np.astype` method was rounding the values in some cases, so we had discrepancies between `nodata` values in bands and general metadata values. For example `nodata: -9.999999933815813e+36` becomes `nodata: "-1e+37"` in bands.
The change simply uses numpy to manage `nan` values, but returning the string representation of the original value in valid cases.
> Fix band nodata value

- raster_loader/io/common.py
- raster_loader/io/snowflake.py
Fixes #
- raster loader must consider compression when [sc-470644]
We were not checking the compression when appending rasters and could end up on situations with part of the raster compressed and part not. I didn't add anything into `update_metadata` as we can keep the original compression value. This PR also fixes a little error in Snowflake where we were not passing the compress to the metadata.
[Anything else you'd like to include.]
> fix: matching compressions should be checked when appending rasters
